### Create fingerprint

POST http://localhost:7000/api/fingerprint
Content-Type: application/json

{
  "email": "dianababurina74@gmail.com",
  "hash": "dlldldld",
  "userId": "dldlkfkfkf"
}

### Get user fingeprints by email

GET http://localhost:7000/api/fingerprint?email=diana.babu7ina@nure.ua&hash=1f448b10ee8b166ee0644d833f5880bf

###
